name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Har raat 12 baje update hoga
  workflow_dispatch: # Aap ise manually bhi chala sakte hain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: 01deepakshukla
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
